### ISSUE TITLE
Need option to stop the current track and release the Camera

### ISSUE THREAD

**Issue by teamforward-in** [mayank8aug/react-image-data-capture#1]
Reference
https://stackoverflow.com/questions/11642926/stop-close-webcam-stream-which-is-opened-by-navigator-mediadevices-getusermedia

**Comment by mayank8aug** [comment]
@teamforward-in, It is already there. You can control it in your implementation. By default it will continue the track allowing you to capture snapshots. If you wish to stop the track, I would suggest to mount the `<ImageCapture />` when needed and unmount once you capture the snapshot, .i.e, in the `onCapture` callback.
Please refer this [sample](https://codesandbox.io/s/react-image-data-capture-5cc5z).

Please let me know if you still face any issue. I will anyway update the documentation to add more clarity on this.

**Comment by mayank8aug** [comment]
The README is upto date now and the given sample sandbox should be referred to unmount the component and stop the track stream.
